version: 2.1

orbs:
    node: circleci/node@4.1.0

jobs:
    tests:
        docker:
            - image: circleci/node:14.15.3-browsers
        steps:
            - checkout
            - node/install-yarn
            - run: node --version
            - run: yarn --version
            - node/install-packages:
                pkg-manager: yarn
            - run: yarn lint

workflows:
    ci:
        jobs:
            - tests
